version: '3.3'

volumes:
    {{cookiecutter.project_slug}}_data: {}

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: sh -c "/wait && /start.sh"
    restart: unless-stopped
    env_file: .env
    environment:
      WAIT_HOSTS: pgbouncer:5439

  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: unless-stopped

  postgres:
    image: kartoza/postgis:12.1
    volumes:
      - {{cookiecutter.project_slug}}_data:/var/lib/postgresql/data
    env_file: .env

  pgbouncer:
    image: pgbouncer/pgbouncer
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "5439:5439"
    env_file: .env
    environment:
      WAIT_HOSTS: postgres:5432
    logging:
      driver: none

{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none
{% endif %}

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
